afs: Remove set but unused cnt in afs_GetDownDSlot()
The `cnt` variable is incremented but never accessed in
afs_GetDownDSlot(). Remove the unused variable.

This fixes a build warning on newer compilers, such as GCC 16.1.1.

    .../src/afs/afs_dcache.c: In function 'afs_GetDownDSlot':
    .../src/afs/afs_dcache.c:1254:18: error: variable 'cnt' set but not used [-Werror=unused-but-set-variable=]
    |     unsigned int cnt;
    |                  ^~~

This bug has been present since OpenAFS 1.0.

Change-Id: I228c7a1b00651fdd38ad946386856865ea126753
Reviewed-on: https://gerrit.openafs.org/16820
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>